import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wade Loccisano Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const theme = "light";
  const theme = "dark";
  return (
    <html lang="en" className={theme === "dark" ? "dark" : "light"}>
      <body className={`${inter.className} + min-h-screen`}>
        {/* <header>The header</header> */}
        <Header />
        {children}
        {/* <footer>The footer</footer> */}
        <Footer />
      </body>
    </html>
  );
}

export function Header() {
  return (
    // <header className="text-center">
    <header className="fixed w-full">
      <section id="header-section" className="bg-white min-h-[60px] shadow-lg">
        <div className="flex flex-row justify-between px-[20rem]">
          <div className="p-2 text-xl">
            Wade Loccisano
          </div>

          {/* <div className="flex flex-row p-2">
            <div>
              Skills
            </div>
            <div>
              Experience
            </div>
            <div>
              Projects
            </div>
            <div>
              Qualifications
            </div>
          </div> */}

          <div className="flex flex-row p-2">
            Contact
            <div>
              Theme
            </div>
          </div>
        </div>
      </section>
    </header>
  );
}

export function Footer() {
  return (
    <footer className="w-full">
      <section id="footer-section" className="bg-white min-h-[60px]">
        <div className="flex flex-row justify-center">
          <div className="text-xl p-4">
            Wade Loccisano
          </div>

          <div className="text-lg p-4">
            About Me
          </div>
          <div className="text-lg p-4">
            About this Site
          </div>
          <div className="text-lg p-4">
            Apps
          </div>
          <div className="text-lg p-4">
            Contact
          </div>

          {/* <Link href="https://www.linkedin.com/in/wade-loccisano/" target="_blank">
            <div className="text-lg p-4">
              About Me
            </div>
          </Link>
          <Link href="https://www.linkedin.com/in/wade-loccisano/" target="_blank">
            <div className="text-lg p-4">
              About this Site
            </div>
          </Link>
          <Link href="https://www.linkedin.com/in/wade-loccisano/" target="_blank">
            <div className="text-lg p-4">
              Apps
            </div>
          </Link>
          <Link href="https://www.linkedin.com/in/wade-loccisano/" target="_blank">
            <div className="text-lg p-4">
              Contact
            </div>
          </Link> */}

        </div>
        <div className="border-t-2 border-slate-200 w-[98%] mx-auto my-0">
        </div>
        <div className="flex flex-row justify-evenly">
          <div className="flex">
            <div className="text-xl p-4">
              {/* Language Select */}
            </div>
            <Link href="/privacy" target="_blank">
              <div className="text-md p-4">
                Privacy Policy
              </div>
            </Link>
            <Link href="/terms" target="_blank">
              <div className="text-md p-4">
                Terms
              </div>
            </Link>
            <div className="text-md p-4">
              Copyright &copy; 2024 Wade Loccisano
            </div>
          </div>
          <div className="flex">
            <Link className="px-2 py-4" href="https://github.com/wade-loccisano" target="_blank">
              <Image
                src="/github-logo.svg"
                alt="Image of the GitHub Logo"
                width={24}
                height={24}
              />
            </Link>
            <Link className="px-2 py-4" href="https://www.linkedin.com/in/wade-loccisano/" target="_blank">
              <Image
                src="/linkedin-logo.svg"
                alt="Image of the LinkedIn Logo"
                width={24}
                height={24}
              />
            </Link>
          </div>
        </div>
      </section>
    </footer>
  );
}