import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wade Loccisano Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const theme = "light";
  const theme = "dark";
  return (
    <html lang="en" className={theme === "dark" ? "dark" : "light"}>
      <body className={`${inter.className} + min-h-screen`}>
        {/* <header>The header</header> */}
        <Header />
        {children}
        {/* <footer>The footer</footer> */}
        <Footer />
      </body>
    </html>
  );
}

export function Header() {
  return (
    // <header className="text-center">
    <header className="fixed w-full">
      <section id="header-section" className="bg-white min-h-[60px]">
        <div className="flex flex-row justify-between px-[20rem]">
          <div className="p-2 text-xl">
            Wade Loccisano
          </div>

          {/* <div className="flex flex-row p-2">
            <div>
              Skills
            </div>
            <div>
              Experience
            </div>
            <div>
              Projects
            </div>
            <div>
              Qualifications
            </div>
          </div> */}

          <div className="flex flex-row p-2">
            Contact
            <div>
              Theme
            </div>
          </div>
        </div>
      </section>
    </header>
  );
}

export function Footer() {
  return (
    <footer className="w-full">
      <section id="footer-section" className="bg-white min-h-[60px]">
        <div className="flex flex-row justify-center">
          <div className="text-xl p-4">
            Wade Loccisano
          </div>
          <div className="text-lg p-4">
            About Me
          </div>
          <div className="text-lg p-4">
            About this Site
          </div>
          <div className="text-lg p-4">
            Apps
          </div>
          <div className="text-lg p-4">
            Contact
          </div>
        </div>
        <div className="border-t-2 border-slate-200 w-[98%] mx-auto my-0">
        </div>
        <div className="flex flex-row justify-evenly">
          <div className="flex">
            <div className="text-xl p-4">
              {/* Language Select */}
            </div>
            <div className="text-md p-4">
              Privacy Policy
            </div>
            <div className="text-md p-4">
              Terms
            </div>
            <div className="text-md p-4">
              Copyright &copy; 2024 Wade Loccisano
            </div>
          </div>
          <div className="flex">
            <div className="text-md p-4">
              Github Icon
            </div>
            <div className="text-md p-4">
              LinkedIn Icon
            </div>
          </div>
        </div>
      </section>
    </footer>
  );
}