name: Deploy Next.js Application

on:
  push:
    branches:
      - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Source
#         uses: actions/checkout@v4
#       - name: Create .env file
#         run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD}}" >> .env
#       - name: Build docker image
#         run: docker build -t wade587/resume-site .
#       - name: Login to Docker Hub
#         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#       - name: Publish Image to Docker Hub
#         run: docker push wade587/resume-site:latest

#   deploy:
#     needs: build
#     runs-on: self-hosted
#     steps:
#       - name: Pull image from docker hub
#         run: docker pull wade587/resume-site:latest
#       - name: Delete old container
#         run: docker rm -f resume-site-container
#       - name: Run docker container
#         run: docker run -d -p 3000:3000 --name resume-site-container wade587/resume-site