name: CI/CD with Terraform
on:
  merge:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets. }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets. }}
  TF_STATE_BUCKET_NAME: ${{ secrets. }}
  PRIVATE_SSH_KEY: ${{ secrets. }}
  PUBLIC_SSH_KEY: ${{ secrets. }}
  AWS_REGION: us-east-1

jobs:
  deploy-infrastructure:
    runs-on: unbuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

# Continue where you left off 
# Complete CI/CD with Terraform and AWS | Terraform Tutorial | DevOps Project | AWS | Cloud-Native - YouTube
# 23:37